object_name: 'Reqres Users - PL'
source_connection_id: 5
enabled: 1

source_settings:
    source_name: "regres"
    resource: "users"
    query_parameters: "page=2"

target_settings:
    target_file_path: "reqres/default/users"
    target_file_name: "users"
    target_file_type: "json"

option_settings:
    record_path: "data"

template_settings:
    template_type: "DataPipeline"
    template_name: "pl_extract_rest_api"

bronze_settings:
    schema_name: reqres
    table_name: default__users

silver_settings:
    schema_name: reqres
    table_name: default__users