object_name: 'Reqres Users'
source_connection_id: 3
enabled: 1

source_system_settings:
    source_name: "regres"
    resource: "users"
    query_parameters:
        page: 2
    primary_keys: ["id"]

extraction_template_settings:
    template_type: "Notebook"
    template_name: "nb_extract_api"

raw_settings:
    target_file_path: "reqres/default/users"
    target_file_name: "users"
    target_file_type: "json"

option_settings:
    record_path: "data"

bronze_settings:
    schema_name: reqres
    table_name: default__users

silver_settings:
    schema_name: reqres
    table_name: default__users
    load_strategy: overwrite