object_name: 'AW SalesOrderHeader'
source_connection_id: 2
enabled: 1

source_system_settings:
    source_type: "sql"
    source_name: "AdventureWorks"
    database_name: "sqldb-adventureworks"
    schema_name: "SalesLT"
    table_name: "SalesOrderHeader"
    primary_keys: ["SalesOrderID"]
    is_incremental: 1
    incremental_column: "ModifiedDate"
    partition_option: "DynamicRange"
    partition_column_name: "YEAR(ModifiedDate)"

extraction_template_settings:
    template_type: "DataPipeline"
    template_name: "pl_extract_sql"

raw_settings:
    target_file_path: "sqldb-adventureworks/SalesLT/SalesOrderHeader"
    target_file_name: "SalesOrderHeader"
    target_file_type: "parquet"

bronze_settings:
    schema_name: sqldb_adventureworks
    table_name: SalesLT__SalesOrderHeader

silver_settings:
    schema_name: sqldb_adventureworks
    table_name: sales_lt__sales_order_header
    load_strategy: merge
