object_name: 'PBI Apps'
source_connection_id: 1
enabled: 1

source_system_settings:
    source_name: "Power BI Tenant"
    resource: "apps"
    query_parameters:
        "$top": 500
    primary_keys: ["id"]

extraction_template_settings:
    template_type: "Notebook"
    template_name: "nb_extract_api"

raw_settings:
    target_file_path: "pbi/default/apps"
    target_file_name: "apps"
    target_file_type: "json"

option_settings:
    record_path: "value"

bronze_settings:
    schema_name: pbi
    table_name: default__apps

silver_settings:
    schema_name: pbi
    table_name: default__apps
    load_strategy: overwrite