object_name: 'AW Address'
source_connection_id: 2
enabled: 1

source_system_settings:
    source_type: "sql"
    source_name: "AdventureWorks"
    database_name: "sqldb-adventureworks"
    schema_name: "SalesLT"
    table_name: "Address"
    primary_keys: ["AddressID"]
    is_incremental: 0
    partition_option: "None"

extraction_template_settings:
    template_type: "DataPipeline"
    template_name: "pl_extract_sql"

extraction_scheduling_settings:
    schedule_type: 'interval'
    frequency_minutes: 1
    skip_if_running: true

raw_settings:
    target_file_path: "sqldb-adventureworks/SalesLT/Address"
    target_file_name: "Address"
    target_file_type: "parquet"

bronze_settings:
    schema_name: sqldb_adventureworks
    table_name: SalesLT__Address

silver_settings:
    schema_name: sqldb_adventureworks
    table_name: sales_lt__address
    load_strategy: overwrite